[ADD] fixed annotation

diff --git a/.github/workflows/ci-coding-style.yml b/.github/workflows/ci-coding-style.yml
--- a/.github/workflows/ci-coding-style.yml
+++ b/.github/workflows/ci-coding-style.yml
@@ -34,5 +34,5 @@ jobs:
           if [[ "$(cat $EXPORT_FILE)" == "" ]]; then
             echo "SUCCESS" && exit 0;
           else 
-            echo "::error:: Missing semicolon" && exit 1;
+            echo "::error::" && cat $EXPORT_FILE && exit 1;
           fi
